import { initializeApp } from 'https://www.gstatic.com/firebasejs/12.19.0/firebase-app.js';
import { getAuth, GoogleAuthProvider, onAuthStateChanged, signInWithPopup, signOut } from 'https://www.gstatic.com/firebasejs/12.19.0/firebase-auth.js';
import { getFirestore, doc, setDoc, updateDoc, onSnapshot, collection, serverTimestamp } from 'https://www.gstatic.com/firebasejs/12.19.0/firebase-firestore.js';

const firebaseConfig = { apiKey:'AIzaSyDKvkPll6GuhR2rXItJ7HuVF7tQ4TmpdGo', authDomain:'stride-strength.firebaseapp.com', projectId:'stride-strength', storageBucket:'stride-strength.firebasestorage.app', messagingSenderId:'928601164915', appId:'1:928601164915:web:eb64de026c96e6f7c96e06' };
const COACH_EMAIL='jsmith@mvcsd.us', ATHLETE_DOMAIN='@stu.mvcsd.us';
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app),provider=new GoogleAuthProvider();
provider.setCustomParameters({prompt:'select_account'});
const initialWorkout={title:'Lower Body Power',focus:'Strength + explosiveness',date:new Date().toISOString().slice(0,10),note:'Move with intent. Full recovery between power sets.',exercises:[{id:1,name:'Back Squat',lift:'squat',sets:4,reps:5,percent:75,rest:'2–3 min'},{id:2,name:'Romanian Deadlift',lift:'deadlift',sets:3,reps:6,percent:60,rest:'2 min'},{id:3,name:'Box Jump',lift:null,sets:4,reps:3,percent:null,rest:'90 sec'},{id:4,name:'Walking Lunge',lift:null,sets:3,reps:'8 / leg',percent:null,rest:'90 sec'}]};
let state={user:null,role:null,athletes:[],workout:initialWorkout,completed:{},selectedId:null,editing:false,loading:true,error:'',unsubs:[]};
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const icon=name=>`<span class="ui-icon">${{home:'⌂',users:'♟',dumbbell:'↔',edit:'✎',check:'✓',plus:'＋',arrow:'→',flame:'▲',logout:'↪'}[name]}</span>`;
const prettyDate=d=>new Intl.DateTimeFormat('en-US',{weekday:'long',month:'long',day:'numeric'}).format(new Date(`${d}T12:00:00`));
const input=(value,action,type='text')=>`<input type="${type}" value="${esc(value)}" data-action="${action}">`;
const initials=(name='Athlete')=>name.split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase();
const athlete=()=>state.role==='athlete'?state.athletes[0]:state.athletes.find(a=>a.id===state.selectedId)||state.athletes[0];
const clearListeners=()=>{state.unsubs.forEach(fn=>fn());state.unsubs=[]};

function loginView(){return `<div class="login-page"><div class="login-card"><div class="brand login-brand"><span class="brand-mark">${icon('flame')}</span><div>STRIDE<span>STRENGTH</span></div></div><p class="eyebrow">TRACK & FIELD TRAINING</p><h1>Your workout.<br>Your numbers.</h1><p class="login-copy">Sign in with your school Google account to see today's strength session.</p><button class="google-button" data-action="signin"><span class="google-g">G</span> Continue with Google</button>${state.error?`<div class="auth-error">${esc(state.error)}</div>`:''}<small>Authorized MVCS district accounts only</small></div><div class="login-art"><div class="art-number">01</div><div><span>BUILT FOR</span><strong>STRONGER<br>ATHLETES.</strong></div></div></div>`}
function loadingView(){return `<div class="loading-page"><span class="brand-mark">${icon('flame')}</span><strong>Loading Stride Strength…</strong></div>`}
function shell(content){const a=athlete(),name=state.role==='coach'?'Coach':(a?.name||state.user.displayName||'Athlete'),avatar=state.role==='coach'?'CO':(a?.initials||initials(name));return `<div class="app-shell"><aside class="sidebar"><div class="brand"><span class="brand-mark">${icon('flame')}</span><div>STRIDE<span>STRENGTH</span></div></div><nav><button class="nav-link active">${icon('home')} Dashboard</button>${state.role==='coach'?`<button class="nav-link">${icon('users')} Athletes <span>${state.athletes.length}</span></button>`:''}<button class="nav-link">${icon('dumbbell')} Max lifts</button></nav><div class="sidebar-bottom"><div class="account-label">SIGNED IN AS</div><div class="account-email">${esc(state.user.email)}</div><button data-action="signout" class="nav-link muted">${icon('logout')} Sign out</button></div></aside><main><header><button class="mobile-brand">${icon('flame')} STRIDE</button><div><p class="eyebrow">${state.role==='coach'?'COACH':'ATHLETE'} DASHBOARD</p><h1>${state.role==='coach'?'Build stronger athletes.':`Ready to work, ${esc(name.split(' ')[0])}?`}</h1></div><div class="profile"><div class="avatar">${esc(avatar)}</div><div><strong>${esc(name)}</strong><span>${state.role==='coach'?'Head Coach':esc(a?.event||'Track & Field')}</span></div></div></header>${content}</main></div>`}
function athleteView(){const a=athlete();if(!a)return `<div class="empty-state"><h2>Setting up your profile…</h2><p>Refresh shortly if this remains.</p></div>`;const w=state.workout,done=w.exercises.filter(ex=>state.completed[ex.id]).length,pct=Math.round(done/w.exercises.length*100)||0;const exercises=w.exercises.map((ex,i)=>{const isDone=state.completed[ex.id],weight=ex.lift?Math.round((a.maxes[ex.lift]*ex.percent/100)/5)*5:null;return `<article class="exercise-card ${isDone?'done':''}"><button class="check-button" data-action="complete" data-id="${ex.id}">${icon('check')}</button><div class="exercise-number">${String(i+1).padStart(2,'0')}</div><div class="exercise-name"><h4>${esc(ex.name)}</h4><span>Rest ${esc(ex.rest)}</span></div><div class="metric"><span>SETS × REPS</span><strong>${ex.sets} × ${esc(ex.reps)}</strong></div><div class="metric target"><span>${weight?`${ex.percent}% OF MAX`:'LOAD'}</span><strong>${weight?`${weight} lb`:'Bodyweight'}</strong></div></article>`}).join('');const maxes=Object.entries(a.maxes).map(([lift,value])=>`<label class="max-row"><span>${lift}</span><div>${input(value,`max-${lift}`,'number')}<small>LB</small></div></label>`).join('');return `<div class="page-grid"><section><div class="date-row"><div><span class="date-dot"></span>${prettyDate(w.date)}</div></div><article class="hero-card"><div class="hero-copy"><p>TODAY'S SESSION</p><h2>${esc(w.title)}</h2><span>${esc(w.focus)}</span></div><div class="progress-ring" style="--progress:${pct*3.6}deg"><div><strong>${done}/${w.exercises.length}</strong><span>DONE</span></div></div></article><div class="section-heading"><h3>Workout</h3><span>${w.exercises.length} exercises</span></div><div class="exercise-list">${exercises}</div><div class="coach-note"><span>COACH'S NOTE</span><p>“${esc(w.note)}”</p></div></section><aside class="right-column"><div class="panel"><div class="panel-title"><div><p>YOUR NUMBERS</p><h3>Current maxes</h3></div>${icon('edit')}</div>${maxes}</div><div class="panel dark-panel"><p>TRAINING TIP</p><h3>Own the movement.</h3><span>Weights are rounded to the nearest 5 lb. Technique always comes before load.</span></div></aside></div>`}
function coachView(){const w=state.workout;const rows=w.exercises.map((ex,i)=>`<div class="builder-row"><span class="builder-num">${i+1}</span><div class="builder-name">${state.editing?input(ex.name,`ex-name-${ex.id}`):`<strong>${esc(ex.name)}</strong>`}<small>${ex.lift?`${ex.percent}% of ${ex.lift} max`:'No max required'}</small></div><label><span>SETS</span>${state.editing?input(ex.sets,`ex-sets-${ex.id}`,'number'):`<b>${ex.sets}</b>`}</label><label><span>REPS</span>${state.editing?input(ex.reps,`ex-reps-${ex.id}`):`<b>${esc(ex.reps)}</b>`}</label></div>`).join('');const roster=state.athletes.length?state.athletes.map(a=>`<div class="athlete-row"><div class="avatar small">${esc(a.initials)}</div><div><strong>${esc(a.name)}</strong><span>${esc(a.event||'Track & Field')}</span></div>${icon('arrow')}</div>`).join(''):`<div class="empty-roster">Athletes appear here after their first sign-in.</div>`;return `<div class="coach-grid"><section><div class="coach-actions"><div><p class="eyebrow">${prettyDate(w.date).toUpperCase()}</p><h2>Today’s workout</h2></div><button class="primary-button" data-action="edit">${icon(state.editing?'check':'edit')} ${state.editing?'Save workout':'Edit workout'}</button></div><article class="builder-card"><div class="builder-header">${state.editing?`${input(w.title,'workout-title')} ${input(w.focus,'workout-focus')}`:`<h3>${esc(w.title)}</h3><span>${esc(w.focus)}</span>`}</div><div>${rows}</div>${state.editing?`<button class="add-button" data-action="add">${icon('plus')} Add exercise</button>`:''}</article></section><aside class="roster"><div class="section-heading"><h3>Team snapshot</h3><span>${state.athletes.length} athletes</span></div>${roster}</aside></div>`}
function render(){document.querySelector('#root').innerHTML=state.loading?loadingView():(!state.user?loginView():shell(state.role==='coach'?coachView():athleteView()))}
async function connectData(){clearListeners();const workoutRef=doc(db,'workouts','current');state.unsubs.push(onSnapshot(workoutRef,async snap=>{if(snap.exists())state.workout=snap.data();else if(state.role==='coach')await setDoc(workoutRef,initialWorkout);render()},()=>{state.error='Could not load the workout. Check the Firestore rules.';render()}));if(state.role==='coach'){state.unsubs.push(onSnapshot(collection(db,'athletes'),snap=>{state.athletes=snap.docs.map(d=>({id:d.id,...d.data()}));state.selectedId=state.athletes[0]?.id;render()}))}else{const athleteRef=doc(db,'athletes',state.user.uid),progressRef=doc(db,'progress',state.user.uid);state.unsubs.push(onSnapshot(athleteRef,async snap=>{if(snap.exists())state.athletes=[{id:snap.id,...snap.data()}];else await setDoc(athleteRef,{name:state.user.displayName||'Athlete',email:state.user.email,event:'Track & Field',initials:initials(state.user.displayName),maxes:{squat:0,bench:0,deadlift:0},createdAt:serverTimestamp()});render()}));state.unsubs.push(onSnapshot(progressRef,snap=>{state.completed=snap.exists()?snap.data().completed||{}:{};render()}))}}
onAuthStateChanged(auth,async user=>{state.loading=false;state.error='';if(!user){state.user=null;state.role=null;clearListeners();render();return}const email=(user.email||'').toLowerCase();if(email===COACH_EMAIL)state.role='coach';else if(email.endsWith(ATHLETE_DOMAIN))state.role='athlete';else{await signOut(auth);state.error=`${email} is not an authorized MVCS account.`;render();return}state.user=user;render();connectData()});
document.addEventListener('click',async e=>{const el=e.target.closest('[data-action]');if(!el)return;const action=el.dataset.action;try{if(action==='signin'){state.error='';render();await signInWithPopup(auth,provider)}if(action==='signout')await signOut(auth);if(action==='complete'){state.completed[el.dataset.id]=!state.completed[el.dataset.id];await setDoc(doc(db,'progress',state.user.uid),{completed:state.completed,updatedAt:serverTimestamp()},{merge:true})}if(action==='edit'){if(state.editing)await setDoc(doc(db,'workouts','current'),state.workout);state.editing=!state.editing}if(action==='add')state.workout.exercises.push({id:Date.now(),name:'New Exercise',lift:null,sets:3,reps:8,percent:null,rest:'90 sec'});render()}catch(err){state.error=err.code==='auth/popup-blocked'?'Allow the Google sign-in popup and try again.':err.message;render()}});
document.addEventListener('change',async e=>{const action=e.target.dataset.action;if(!action)return;if(action.startsWith('max-')){const lift=action.slice(4),a=athlete();a.maxes[lift]=Number(e.target.value);await updateDoc(doc(db,'athletes',state.user.uid),{[`maxes.${lift}`]:a.maxes[lift]})}if(action==='workout-title')state.workout.title=e.target.value;if(action==='workout-focus')state.workout.focus=e.target.value;const match=action.match(/^ex-(name|sets|reps)-(\d+)$/);if(match){const ex=state.workout.exercises.find(x=>x.id===Number(match[2]));ex[match[1]]=match[1]==='sets'?Number(e.target.value):e.target.value}render()});
render();
