const initialAthletes = [
  { id: 1, name: 'Maya Johnson', event: 'Sprints', initials: 'MJ', maxes: { squat: 185, bench: 105, deadlift: 225 } },
  { id: 2, name: 'Eli Carter', event: 'Jumps', initials: 'EC', maxes: { squat: 245, bench: 155, deadlift: 295 } },
  { id: 3, name: 'Sofia Brooks', event: 'Distance', initials: 'SB', maxes: { squat: 135, bench: 75, deadlift: 165 } },
];
const initialWorkout = { title:'Lower Body Power', focus:'Strength + explosiveness', date:new Date().toISOString().slice(0,10), note:'Move with intent. Full recovery between power sets.', exercises:[
  {id:1,name:'Back Squat',lift:'squat',sets:4,reps:5,percent:75,rest:'2–3 min'},
  {id:2,name:'Romanian Deadlift',lift:'deadlift',sets:3,reps:6,percent:60,rest:'2 min'},
  {id:3,name:'Box Jump',lift:null,sets:4,reps:3,percent:null,rest:'90 sec'},
  {id:4,name:'Walking Lunge',lift:null,sets:3,reps:'8 / leg',percent:null,rest:'90 sec'}
]};
const load=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))||fallback}catch{return fallback}};
let state={role:localStorage.getItem('stride-role')||'athlete',athletes:load('stride-athletes',initialAthletes),workout:load('stride-workout',initialWorkout),completed:load('stride-completed',{}),selectedId:1,editing:false};
const save=()=>{localStorage.setItem('stride-role',state.role);localStorage.setItem('stride-athletes',JSON.stringify(state.athletes));localStorage.setItem('stride-workout',JSON.stringify(state.workout));localStorage.setItem('stride-completed',JSON.stringify(state.completed))};
const esc=(s)=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const icon=(name)=>`<span class="ui-icon">${{home:'⌂',users:'♟',dumbbell:'↔',edit:'✎',check:'✓',plus:'＋',arrow:'→',flame:'▲',logout:'↪'}[name]}</span>`;
const prettyDate=(d)=>new Intl.DateTimeFormat('en-US',{weekday:'long',month:'long',day:'numeric'}).format(new Date(`${d}T12:00:00`));
const athlete=()=>state.athletes.find(a=>a.id===state.selectedId)||state.athletes[0];
const input=(value,action,type='text')=>`<input type="${type}" value="${esc(value)}" data-action="${action}">`;

function shell(content){const a=athlete();return `<div class="app-shell"><aside class="sidebar"><div class="brand"><span class="brand-mark">${icon('flame')}</span><div>STRIDE<span>STRENGTH</span></div></div><nav><button class="nav-link active">${icon('home')} Dashboard</button>${state.role==='coach'?`<button class="nav-link">${icon('users')} Athletes <span>${state.athletes.length}</span></button>`:''}<button class="nav-link">${icon('dumbbell')} Max lifts</button></nav><div class="sidebar-bottom"><div class="demo-label">DEMO VIEW</div><div class="role-switch"><button data-action="role-athlete" class="${state.role==='athlete'?'selected':''}">Athlete</button><button data-action="role-coach" class="${state.role==='coach'?'selected':''}">Coach</button></div><button class="nav-link muted">${icon('logout')} Sign out</button></div></aside><main><header><button class="mobile-brand" data-action="toggle-role">${icon('flame')} STRIDE</button><div><p class="eyebrow">${state.role==='coach'?'COACH':'ATHLETE'} DASHBOARD</p><h1>${state.role==='coach'?'Build stronger athletes.':`Ready to work, ${esc(a.name.split(' ')[0])}?`}</h1></div><div class="profile"><div class="avatar">${state.role==='coach'?'CO':esc(a.initials)}</div><div><strong>${state.role==='coach'?'Coach':esc(a.name)}</strong><span>${state.role==='coach'?'Head Coach':esc(a.event)}</span></div></div></header>${content}</main></div>`}

function athleteView(){const a=athlete(),w=state.workout,done=w.exercises.filter(ex=>state.completed[`${a.id}-${ex.id}`]).length,pct=Math.round(done/w.exercises.length*100)||0;const exercises=w.exercises.map((ex,i)=>{const isDone=state.completed[`${a.id}-${ex.id}`],weight=ex.lift?Math.round((a.maxes[ex.lift]*ex.percent/100)/5)*5:null;return `<article class="exercise-card ${isDone?'done':''}"><button class="check-button" data-action="complete" data-id="${ex.id}">${icon('check')}</button><div class="exercise-number">${String(i+1).padStart(2,'0')}</div><div class="exercise-name"><h4>${esc(ex.name)}</h4><span>Rest ${esc(ex.rest)}</span></div><div class="metric"><span>SETS × REPS</span><strong>${ex.sets} × ${esc(ex.reps)}</strong></div><div class="metric target"><span>${weight?`${ex.percent}% OF MAX`:'LOAD'}</span><strong>${weight?`${weight} lb`:'Bodyweight'}</strong></div></article>`}).join('');const maxes=Object.entries(a.maxes).map(([lift,value])=>`<label class="max-row"><span>${lift}</span><div>${input(value,`max-${lift}`,'number')}<small>LB</small></div></label>`).join('');return `<div class="page-grid"><section class="primary-column"><div class="date-row"><div><span class="date-dot"></span>${prettyDate(w.date)}</div><select data-action="athlete-select">${state.athletes.map(x=>`<option value="${x.id}" ${x.id===a.id?'selected':''}>${esc(x.name)}</option>`).join('')}</select></div><article class="hero-card"><div class="hero-copy"><p>TODAY'S SESSION</p><h2>${esc(w.title)}</h2><span>${esc(w.focus)}</span></div><div class="progress-ring" style="--progress:${pct*3.6}deg"><div><strong>${done}/${w.exercises.length}</strong><span>DONE</span></div></div></article><div class="section-heading"><h3>Workout</h3><span>${w.exercises.length} exercises</span></div><div class="exercise-list">${exercises}</div><div class="coach-note"><span>COACH'S NOTE</span><p>“${esc(w.note)}”</p></div></section><aside class="right-column"><div class="panel"><div class="panel-title"><div><p>YOUR NUMBERS</p><h3>Current maxes</h3></div>${icon('edit')}</div>${maxes}</div><div class="panel dark-panel"><p>TRAINING TIP</p><h3>Own the movement.</h3><span>Weights are rounded to the nearest 5 lb. Technique always comes before load.</span></div></aside></div>`}

function coachView(){const w=state.workout;const rows=w.exercises.map((ex,i)=>`<div class="builder-row"><span class="builder-num">${i+1}</span><div class="builder-name">${state.editing?input(ex.name,`ex-name-${ex.id}`):`<strong>${esc(ex.name)}</strong>`}<small>${ex.lift?`${ex.percent}% of ${ex.lift} max`:'No max required'}</small></div><label><span>SETS</span>${state.editing?input(ex.sets,`ex-sets-${ex.id}`,'number'):`<b>${ex.sets}</b>`}</label><label><span>REPS</span>${state.editing?input(ex.reps,`ex-reps-${ex.id}`):`<b>${esc(ex.reps)}</b>`}</label></div>`).join('');const roster=state.athletes.map(a=>`<div class="athlete-row"><div class="avatar small">${esc(a.initials)}</div><div><strong>${esc(a.name)}</strong><span>${esc(a.event)}</span></div>${icon('arrow')}</div>`).join('');return `<div class="coach-grid"><section><div class="coach-actions"><div><p class="eyebrow">${prettyDate(w.date).toUpperCase()}</p><h2>Today’s workout</h2></div><button class="primary-button" data-action="edit">${icon(state.editing?'check':'edit')} ${state.editing?'Save workout':'Edit workout'}</button></div><article class="builder-card"><div class="builder-header">${state.editing?`${input(w.title,'workout-title')} ${input(w.focus,'workout-focus')}`:`<h3>${esc(w.title)}</h3><span>${esc(w.focus)}</span>`}</div><div class="builder-list">${rows}</div>${state.editing?`<button class="add-button" data-action="add">${icon('plus')} Add exercise</button>`:''}</article></section><aside class="roster"><div class="section-heading"><h3>Team snapshot</h3><span>${state.athletes.length} athletes</span></div>${roster}</aside></div>`}

function render(){document.querySelector('#root').innerHTML=shell(state.role==='coach'?coachView():athleteView())}
document.addEventListener('click',e=>{const el=e.target.closest('[data-action]');if(!el)return;const action=el.dataset.action;if(action.startsWith('role-'))state.role=action.split('-')[1];if(action==='toggle-role')state.role=state.role==='coach'?'athlete':'coach';if(action==='complete'){const key=`${state.selectedId}-${el.dataset.id}`;state.completed[key]=!state.completed[key]}if(action==='edit')state.editing=!state.editing;if(action==='add')state.workout.exercises.push({id:Date.now(),name:'New Exercise',lift:null,sets:3,reps:8,percent:null,rest:'90 sec'});save();render()});
document.addEventListener('change',e=>{const action=e.target.dataset.action;if(!action)return;if(action==='athlete-select')state.selectedId=Number(e.target.value);if(action.startsWith('max-'))athlete().maxes[action.slice(4)]=Number(e.target.value);if(action==='workout-title')state.workout.title=e.target.value;if(action==='workout-focus')state.workout.focus=e.target.value;const match=action.match(/^ex-(name|sets|reps)-(\d+)$/);if(match){const ex=state.workout.exercises.find(x=>x.id===Number(match[2]));ex[match[1]]=match[1]==='sets'?Number(e.target.value):e.target.value}save();render()});
render();
